import type { Metadata } from 'next'

import { fontSans } from '@/libs/fonts'

import '../styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontSans.className}>
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
